version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${ROOT}/config/nginx/conf-d:/etc/nginx/conf.d
      - ${ROOT}/config/nginx/conf:/etc/nginx/conf
      - ${ROOT}/config/nginx/dhparams.pem:/etc/nginx/dhparams.pem
      - ${ROOT}/config/letsencrypt/etc/letsencrypt:/certs

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=scottyskidmore.com
      - SUBDOMAINS=wildcard,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=scotty.skidmore@gmail.com
      - DHLEVEL=4096
    volumes:
      - ${ROOT}/config/letsencrypt:/config
    restart: unless-stopped

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: "-r 192.168.1.0/24" # route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    # ports:
    #   - 8112:8112
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
      - /mnt/d/TV Shows:/tv_d # deadpool spcific dirs
      - /mnt/g/TV Shows:/tv_g # deadpool spcific dirs

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
      - /mnt/e/Movies:/movies_e # deadpool spcific dirs

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
      - /mnt/g/TV Shows:/tv_g # deadpool spcific dirs
      - /mnt/e/Movies:/movies_e # deadpool spcific dirs
      - /mnt/d/TV Shows:/tv_d # deadpool spcific dirs
      - /mnt/e/Audiobooks:/audiobooks_e # deadpool spcific dirs

    
  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/organizr:/config # config files
  
  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/overseerr:/config # config files

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop # no master branch avaliable at this time
    # version: develop
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/prowlarr:/config # config files

  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/tautulli:/config # config files
  
  requestrr:
    container_name: requestrr 
    image: darkalfx/requestrr:latest
    restart: unless-stopped
    ports:
      - 4545:4545
    volumes:
      - ${ROOT}/config/requestrr:/root/config # config files

networks:
  default:
    driver: bridge